# git aliases
alias ga="git add"
alias gb="git branch"
alias gbd="git branch -D"
alias gbm="gb -m"
alias gc="git clone"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcod="git checkout dev"
alias gcom="git checkout main"
alias gcm="git commit -m"
alias gdd="git branch | grep -v 'main' | xargs git branch -D"
alias gfu="git fetch upstream"
alias gh='clear && git log --color --pretty=format:"%C(yellow)%h%C(reset) %s%C(bold red)%d%C(reset) %C(green)%ad%C(reset) %C(blue)[%an]%C(reset)" --relative-date --decorate'
alias gk="gitk"
alias gl='clear && git log --oneline --decorate'
alias gmu="git merge upstream/main"
alias gp="git push"
alias gpf="git push -f"
alias gr="git remote"
alias grv="git remote -v"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias grh="git reset --hard HEAD"
alias grod="git rebase -i origin/dev"
alias grom="git rebase -i origin/main"
alias grum="git rebase -i upstream/main"
alias grs="git rebase --skip"
alias gs="git status"

# npm aliases
alias npb="npm run build"
alias npc="npm run clean"
alias npd="npm run deploy"
alias npdp="npm run deploy:prod"
alias npdb="npm run docker:build"
alias npdn="npm run docker:nuke"
alias npds="npm run docker:start"
alias npdst="npm run docker:stop"
alias nppd="npm run pre-deploy"
alias npr="npm run"
alias nps="npm start"
alias npst="npm stop"
alias npt="npm test"
alias npmr="npm repo"
